- hosts: localhost
  become: yes
  tasks:
    - name: Create list
      set_fact:
        host_list: "{{ host_list|default([]) }} + ['web-{{ item }}']"
      with_sequence: count=10

    - name: Create directories
      file:
        path: /data/{{ item }}
        state: directory
      with_items: "{{ host_list }} + ['loadbalancer']"

    - name: Create html files
      copy:
        content: "{{ item }}\n"
        dest: /data/{{ item }}/index.html
      with_items: "{{ host_list }}"

    - name: Place nginx configuration
      copy:
        src: nginx_config
        dest: /data/loadbalancer/loadbalancer.conf

    - name: Start Webservers
      docker_container:
        hostname: "{{ item }}"
        name: "{{ item }}"
        state: started
        image: nginx:alpine
        restart_policy: always
        volumes:
          - "/data/{{ item }}:/usr/share/nginx/html"
      with_items: "{{ host_list }}"

    - name: Create host-pairs
      set_fact:
        etc_hosts: "{{ etc_hosts|default({}) | combine( {item : item } ) }}"
      with_items: "{{ host_list }}"

    - name: Start Load-balancer
      docker_container:
        hostname: loadbalancer
        name: loadbalancer
        state: started
        image: nginx:alpine
        restart_policy: always
        etc_hosts: "{{ etc_hosts }}"
        links: "{{ host_list }}"
        volumes:
          - "/data/loadbalancer:/etc/nginx/conf.d"
        ports:
          - "80:80"
